### PR TITLE
Update to v3

### PR DESCRIPTION
**Pull request by jimmydorry**
Here you go buddy.

You will want to test this in workshop tools (change settings.kv TESTING to true, temporarily) before pushing.

### CODE REVIEW

**Comment by litianren001** [comment]
Thanks!

**Comment by litianren001** [comment]
i've updated. seems good. :)


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: jimmydorry <notifications@github.com> </div><div>Date:11/11/2015  6:46 PM  (GMT-06:00) </div><div>To: litianren001/ags_685 <ags_685@noreply.github.com> </div><div>Cc:  </div><div>Subject: [ags_685] Update to v3 (#2) </div><div>
</div>Here you go buddy.

You will want to test this in workshop tools (change settings.kv TESTING to true, temporarily) before pushing.

You can view, comment on, or merge this pull request online at:

  https://github.com/litianren001/ags_685/pull/2

Commit Summary

add v3 client check-in
add v3 client check-in
Update MIN_PLAYERS to 4
Update schema
Update init.lua
Update utilities.lua
Delete statcollection.lua.bak
Update main library file to v3
Delete schema.lua.bak
Delete settings.kv.bak
Update schemaID
File Changes

A content/dota_addons/ags_685/panorama/layout/custom_game/statcollection.xml (6)
A content/dota_addons/ags_685/panorama/scripts/custom_game/statcollection.js     (40)
M game/dota_addons/ags_685/scripts/vscripts/statcollection/init.lua (6)
M game/dota_addons/ags_685/scripts/vscripts/statcollection/lib/statcollection.lua (49)
D game/dota_addons/ags_685/scripts/vscripts/statcollection/lib/statcollection.lua.bak (542)
M game/dota_addons/ags_685/scripts/vscripts/statcollection/lib/utilities.lua (15)
M game/dota_addons/ags_685/scripts/vscripts/statcollection/schema.lua (50)
D game/dota_addons/ags_685/scripts/vscripts/statcollection/schema.lua.bak (136)
M game/dota_addons/ags_685/scripts/vscripts/statcollection/settings.kv (4)
D game/dota_addons/ags_685/scripts/vscripts/statcollection/settings.kv.bak (25)
Patch Links:

https://github.com/litianren001/ags_685/pull/2.patch
https://github.com/litianren001/ags_685/pull/2.diff

**Comment by jimmydorry** [comment]
Great!

**Comment by litianren001** [comment]
So far there seems to be 3 problems:
1) I've set MIN_PLAYER to 8, and find some 10 players games only have 9 players in record. e.g. http://getdotastats.com/#s2__match?id=1936767
2) detailed player performance unavailable.
3) Flags, game values, player values, winrates all unavailable.

**Comment by litianren001** [comment]
problem 1:
Just wrong display. The match id is 1930791210. Exactly a 9 players game. Noob host, lol.

**Comment by jimmydorry** [comment]
1. Even 8 is way too high.
2. I think the game linked has a bot (non player)
3. If you schema part is not working, u dont get the detailed stats. Run it locally in workshop tools and see if there is an error.
4. If you aren't recording the data, there is nothing to display.

**Comment by jimmydorry** [comment]
Can you clear your console, play for 5Mins, then run test_schema in console?

The console for a full game might tell us something interesting too.

**Comment by litianren001** [comment]
[   VScript              ]: -------- GAME DATA --------
[   VScript              ]: {
[   VScript              ]:    gw                              	= "NULL" (string)
[   VScript              ]: }
[   VScript              ]: 
[   VScript              ]: -------- PLAYER DATA --------
[   VScript              ]: {
[   VScript              ]:    1                               	= table: 0x001cadf0 (table)
[   VScript              ]:    {
[   VScript              ]:       pk                              	= 0 (number)
[   VScript              ]:       pt                              	= "Radiant" (string)
[   VScript              ]:       ph                              	= "pugna" (string)
[   VScript              ]:       pnw                             	= 17106 (number)
[   VScript              ]:       pl                              	= 25 (number)
[   VScript              ]:       steamID32                       	= 161697269 (number)
[   VScript              ]:       pa                              	= 0 (number)
[   VScript              ]:       pd                              	= 0 (number)
[   VScript              ]:    }
[   VScript              ]: }
[   VScript              ]: -------------------------------------

**Comment by jimmydorry** [comment]
Gonna need the whole log for a full game then, i guess. There should be lines that start with stat collection, which will tell us where it goes wrong.

**Comment by jimmydorry** [comment]
Will look here again tomorrow.

**Comment by litianren001** [comment]
[   VScript              ]: Stat Collection: The server said something went wrong, see below:
[   VScript              ]: Caught Exception: Missing `is1` from Round `0` in Player array!
[   General              ]: SIGNOUT: Permission granted by GC.
[   VScript              ]: Stat Collection: Match stats were successfully recorded!

**Comment by litianren001** [comment]
Ok.

**Comment by litianren001** [comment]
Seems item info not collected

**Comment by jimmydorry** [comment]
And your console log confirms that.

**Comment by jimmydorry** [comment]
Change the nil to -1 and see if that fixes. https://github.com/litianren001/ags_685/blob/master/game/dota_addons/ags_685/scripts/vscripts/statcollection/lib/utilities.lua#L59

**Comment by jimmydorry** [comment]
herwise, you need to figure out why the slots are not in your schema data.

**Comment by litianren001** [comment]
yes. i tried but it doesn't work.
By adding print I find the function functional.
[   VScript              ]: 0	 	item_tango
[   VScript              ]: tango
[   VScript              ]: 1	 	item_flask
[   VScript              ]: flask
[   VScript              ]: 2	 	item_smoke_of_deceit
[   VScript              ]: smoke_of_deceit

function GetItemSlot(hero,slot)
    local item = hero:GetItemInSlot(slot)
    if item then
    		--print(slot,item:GetAbilityName())
        local itemName = string.gsub(item:GetAbilityName(),"item_","")
        --print(itemName)
    end
    
    return itemName
end

**Comment by litianren001** [comment]
gotcha.del "local" in local itemName = string.gsub(item:GetAbilityName(),"item_","")

**Comment by litianren001** [comment]
function GetItemSlot(hero,slot)
    local item = hero:GetItemInSlot(slot)
    local itemName = ""
    if item then
        itemName = string.gsub(item:GetAbilityName(),"item_","")
    end
    print (itemName)
    return itemName
end

-----------

[                        ]: ] test_schema
[   VScript              ]: courier
[   VScript              ]: tpscroll
[   VScript              ]: smoke_of_deceit
[   VScript              ]: 
[   VScript              ]: 
[   VScript              ]: 
[   VScript              ]: -------- GAME DATA --------
[   VScript              ]: {
[   VScript              ]:    gw                              	= "NULL" (string)
[   VScript              ]: }
[   VScript              ]: 
[   VScript              ]: -------- PLAYER DATA --------
[   VScript              ]: {
[   VScript              ]:    1                               	= table: 0x004341c8 (table)
[   VScript              ]:    {
[   VScript              ]:       is6                             	= "" (string)
[   VScript              ]:       pk                              	= 0 (number)
[   VScript              ]:       pt                              	= "Radiant" (string)
[   VScript              ]:       ph                              	= "pugna" (string)
[   VScript              ]:       pnw                             	= 625 (number)
[   VScript              ]:       is1                             	= "courier" (string)
[   VScript              ]:       pl                              	= 1 (number)
[   VScript              ]:       is5                             	= "" (string)
[   VScript              ]:       steamID32                       	= 161697269 (number)
[   VScript              ]:       is4                             	= "" (string)
[   VScript              ]:       is3                             	= "smoke_of_deceit" (string)
[   VScript              ]:       pa                              	= 0 (number)
[   VScript              ]:       pd                              	= 0 (number)
[   VScript              ]:       is2                             	= "tpscroll" (string)
[   VScript              ]:    }
[   VScript              ]: }
[   VScript              ]: -------------------------------------

**Comment by litianren001** [comment]
http://getdotastats.com/#s2__match?id=1937982

**Comment by jimmydorry** [comment]
Make a PR for updated utilities.lua in main lib. Good work.

**Comment by litianren001** [comment]
still some records undocumented. To ensure no nil, I do like this:
https://github.com/litianren001/ags_685/blob/master/game/dota_addons/ags_685b/scripts/vscripts/statcollection/schema.lua#L74-L80

**Comment by litianren001** [comment]
can't figure out why fail to record some schema, while some others can. 

http://getdotastats.com/#s2__match?id=1947279
http://getdotastats.com/#s2__match?id=1947860

**Comment by jimmydorry** [comment]
No idea. Can't do anything without logs. I suggest double check the schema to make sure it is always populated.

**Pull request merged**
